#!/bin/bash

HISTSIZE=10000
SAVEHIST=10000

export PATH="${HOME}/.local/bin":$PATH
export PATH="${HOME}/.cargo/bin:$PATH"
export PATH="${HOME}/neovim/bin:${PATH}"

export PATH="$PATH:/home/sj/.local/share/coursier/bin"
